# Generated by Django 6.0 on 2026-01-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
    ]
